# Workflow Name
name: Deploy to heruko

# Run workflow on every push to main branch
on:
  push:
    branches: [main]

# Workflow jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository
      - name: Checkout
        uses: actions/checkout@v2


      - name: Build, Push and Release a Docker container to Heroku # Custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # Github action name 
        with:

          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
